-d C:\Users\mrsa2\Projects\GoWin\tang-nano-templates\TangNano-9K-LCD-TripComp\impl\gwsynthesis\Tang_nano_9K_LCD_TripComp.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\mrsa2\Projects\GoWin\tang-nano-templates\TangNano-9K-LCD-TripComp\src\Tang_nano_9K_LCD_TripComp.cst
-cfg C:\Users\mrsa2\Projects\GoWin\tang-nano-templates\TangNano-9K-LCD-TripComp\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-correct_hold 1
-route_maxfan 23
