-d C:\Users\mrsa2\Projects\GoWin\tang-nano-templates\hdmi_terminal_uart\impl\gwsynthesis\hdmi_terminal_uart.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Users\mrsa2\Projects\GoWin\tang-nano-templates\hdmi_terminal_uart\src\Nano4K_HDMI.cst
-cfg C:\Users\mrsa2\Projects\GoWin\tang-nano-templates\hdmi_terminal_uart\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
